apiVersion: v2
name: app
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"



dependencies:
- name: database
  version: 0.1.0
  repository: file://../database   #this is the location of the database chart (one level back)
  tags:
  - database
